[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
cache_path = "cache_forge"
libs = ["lib", "node_modules"]
solc_version = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
remappings = [
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@gluwa/usc-contracts/=node_modules/@gluwa/usc-contracts/",
  "forge-std/=lib/forge-std/src/"
]

[invariant]
runs = 128
depth = 32
fail_on_revert = false
call_override = false

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
creditcoin_cc3 = "https://rpc.cc3-testnet.creditcoin.network"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }
creditcoin_cc3 = { key = "${BLOCKSCOUT_API_KEY}", chain = 102031, url = "https://creditcoin-testnet.blockscout.com/api" }
